services:
  web-sub-client:
    image: modfin/websub-client:latest
    ports:
      - "9998:9998"
    environment:
      - HOSTNAME=web-sub-client
      - PORT=9998
      - HUB_URL=http://hub:9999
      - TOPIC=a-topic

  hub:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
